# Generated by Django 5.2.8 on 2025-12-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
