# Generated by Django 5.2.8 on 2025-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_categoria_remove_libro_disponible_libro_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('vencido', 'Vencido')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='renovaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
