# Generated by Django 5.2.8 on 2026-01-05 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='pagada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_socio',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto'), ('multado', 'Multado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_prestamo', 'Crear Préstamo'), ('finalizar_prestamo', 'Finalizar Préstamo'), ('renovar_prestamo', 'Renovar Préstamo'), ('pagar_multa', 'Pagar Multa'), ('crear_libro', 'Crear Libro'), ('crear_autor', 'Crear Autor')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('prestamo_id', models.IntegerField(blank=True, null=True)),
                ('multa_id', models.IntegerField(blank=True, null=True)),
                ('libro_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
