# Generated by Django 5.2.8 on 2026-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_multa_codigo_multa_fecha_pago_multa_pagada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto'), ('multado', 'Multado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20),
        ),
    ]
