# Generated by Django 5.2.8 on 2026-01-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_prestamos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear_prestamo', 'Crear Préstamo'), ('finalizar_prestamo', 'Finalizar Préstamo'), ('renovar_prestamo', 'Renovar Préstamo'), ('pagar_multa', 'Pagar Multa'), ('crear_libro', 'Crear Libro'), ('crear_autor', 'Crear Autor'), ('crear_usuario', 'Crear Usuario'), ('inicio_sesion', 'Inicio de Sesión'), ('cierre_sesion', 'Cierre de Sesión')], max_length=50),
        ),
    ]
